# Generated by Django 5.2. This migration is kept in the repository so a
# future team can bootstrap the database with `python manage.py migrate`.
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                ("category", models.CharField(choices=[("build", "Build log"), ("competition", "Competition"), ("people", "People"), ("process", "Process")], default="build", max_length=20)),
                ("excerpt", models.TextField(max_length=320)),
                ("body", models.TextField(help_text="Plain text is supported; use blank lines for paragraphs.")),
                ("featured_image_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-published_at"]},
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("season", models.CharField(help_text="e.g. 2026", max_length=32)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                ("top_speed", models.CharField(blank=True, max_length=40)),
                ("acceleration", models.CharField(blank=True, help_text="e.g. 0–60 mph", max_length=40)),
                ("peak_power", models.CharField(blank=True, max_length=40)),
                ("accumulator", models.CharField(blank=True, max_length=60)),
                ("chassis", models.CharField(blank=True, max_length=80)),
                ("featured", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-season", "-is_current", "name"]},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("date", models.DateField()),
                ("time", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("registration_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={"ordering": ["date", "title"]},
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("caption", models.CharField(blank=True, max_length=240)),
                ("image_url", models.URLField()),
                ("alt_text", models.CharField(max_length=180)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={"ordering": ["-published_at"]},
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("tier", models.CharField(choices=[("champion", "Champion"), ("builder", "Builder"), ("partner", "Partner"), ("supporter", "Supporter")], default="partner", max_length=20)),
                ("website", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["tier", "sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("subteam", models.CharField(choices=[("aero", "Aerodynamics"), ("battery", "Battery & HV"), ("controls", "Controls & Software"), ("drivetrain", "Drivetrain"), ("chassis", "Chassis & Vehicle Dynamics"), ("business", "Business & Operations")], max_length=24)),
                ("year", models.CharField(blank=True, help_text="e.g. Class of 2027", max_length=32)),
                ("bio", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("joined_year", models.PositiveIntegerField(blank=True, null=True)),
                ("is_lead", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"], "verbose_name": "team member", "verbose_name_plural": "team members"},
        ),
    ]

